site: Sidey
url: ''
title: Sidey
description: Simple and minimalistic jekyll blogging theme.
twitter:
  username: null
  card: summary
  creator: null
author:
  twitter: null
  name: null
  avatar: null
  email: null
  url: null
permalink: pretty
baseurl: ''
highlighter: none
exclude:
  - .jekyll-cache
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
sass:
  sass_dir: _sass
  style: ':compressed'
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  pages:
    output: true
    permalink: '/:name'
  posts:
    output: true
    permalink: '/:year/:month/:day/:slug'
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
